language: node_js
node_js:
  - 10.15.3
cache: yarn

#before_intall:
install:
  - yarn install
#before_script:
script:
 - yarn test
 - yarn run build
#after_success:
#after_failure:
#after_script:
#before_deploy:
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages
#after_deploy: